name: Deploy to OVH

on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build production
        run: yarn build:app:docker
        env:
          NODE_ENV: production

      - name: Prepare deployment files
        run: |
          cd excalidraw-app/build
          # Create list of files to deploy
          find . -type f > ../../deploy-files.txt

      - name: Install deployment tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Test SFTP connection
        run: |
          echo "Testing SFTP connection..."
          echo '${{ secrets.OVH_PASSWORD }}' > /tmp/sftp_pass
          sshpass -f /tmp/sftp_pass sftp -o StrictHostKeyChecking=no -o PreferredAuthentications=password ${{ secrets.OVH_USERNAME }}@${{ secrets.OVH_HOST }} << EOF
          pwd
          ls -la
          quit
          EOF
          rm /tmp/sftp_pass

      - name: Deploy to OVH via SFTP
        run: |
          echo "Starting deployment to /excalidraw/..."

          # Utiliser fichier temporaire pour le mot de passe
          echo '${{ secrets.OVH_PASSWORD }}' > /tmp/sftp_pass

          # Utiliser sftp pour déployer
          sshpass -f /tmp/sftp_pass sftp -o StrictHostKeyChecking=no -o PreferredAuthentications=password ${{ secrets.OVH_USERNAME }}@${{ secrets.OVH_HOST }} << EOF
          # Naviguer vers le répertoire web
          cd www

          # Créer le dossier excalidraw s'il n'existe pas
          mkdir excalidraw
          cd excalidraw

          # Changer vers le dossier local du build
          lcd excalidraw-app/build

          # Uploader tous les fichiers
          put -r * .

          # Vérifier le déploiement
          ls -la
          quit
          EOF

          # Nettoyer le fichier de mot de passe
          rm /tmp/sftp_pass

          echo "Deployment completed!"

      - name: Deployment status
        if: success()
        run: echo "✅ Successfully deployed Excalidraw to OVH!"
